(defun likelyhood (this seen)
  (let ((prob 1))
    (dolist (el this)
      (let ((s 0)(d 0))
	(dohash (key value (nth (position el this) seen))
	  (if (member el key)
	      (progn (setf s (+ s value))
		     (setf d (+ d value)))
	      (setf d (+ d value))))
	(if (> 1 (/ s d))
	    (setf prob (* prob (/ s d))))))
    prob))

; (likelyhood '(RAINY 71 90 TRUE NO) (test-count-tot (weather-numerics)))

